spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
      chat:
        options:
          model: ${OPENAI_CHAT_MODEL:gpt-4o-mini}
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
