name: 이슈 등록
description: 버그 리포트, 기능 요청, 개선 사항 등 모든 이슈를 등록합니다
title: "[이슈 유형] 간단한 제목"
labels: []
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: 이슈 유형
      description: 이슈의 유형을 선택해주세요
      options:
        - feat (새로운 기능 추가)
        - fix (버그 수정)
        - design (UI 디자인 변경)
        - docs (문서 변경)
        - chore (빌드 설정, 의존성, 환경 설정)
        - refactor (코드 리팩토링/성능 개선)
        - test (테스트 코드)
        - comment (주석)
        - style (코드 포맷팅)
        - remove (파일/기능 제거)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 설명
      description: 이슈에 대한 설명을 작성해주세요
      placeholder: |
        - 버그인 경우: 어떤 문제가 발생했나요?
        - 기능인 경우: 어떤 기능이 필요한가요?
        - 개선인 경우: 무엇을 개선하고 싶나요?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 추가 정보
      description: 스크린샷, 로그, 참고 자료 등을 추가해주세요
      placeholder: |
        - 재현 방법
        - 예상 동작
        - 환경 정보
        - 관련 파일/코드
    validations:
      required: false
